# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/den.yml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseDen(HttpRunner):
    @pytest.mark.parametrize("param", Parameters({"mobile-password": "${P(data.csv)}"}))
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("土豆雅思接口测试")
        .variables(
            **{"version": "2.29.0", "mobile": 13041201075, "password": "9DDEFA27"}
        )
        .base_url("https://eappser.todoen.com")
    )

    teststeps = [
        Step(
            RunRequest("登录")
            .post("/user/login/password")
            .with_json({"mobile": "$mobile", "password": "$password"})
            .extract()
            .with_jmespath("body.data.id", "uid")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.msg", "登录成功")
        ),
        Step(
            RunRequest("用户信息")
            .get("/userinfo/index")
            .with_headers(
                **{"tokenid": "${int_to_str($uid)}", "Content-Type": "application/json"}
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("金刚区")
            .get("/home/learn/list")
            .with_headers(**{"version": "$version"})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseDen().test_start()
